vnnerdata = [(u"Fenqing là gì ?", {"entities": [(0, 7, "PER")]}),
            (u"Không thể hiểu được Trung Quốc nếu không biết Fenqing là gì và họ đóng vai trò gì trong xã hội Trung Quốc ngày nay .", {"entities": [(20, 30, "LOC"),(46, 53, "PER"),(95, 105, "LOC")]}),
            (u"Trong bài viết này , tôi sẽ cố phác hoạ chân dung một Fenqing .", {"entities": [(54, 61, "PER")]}),
            (u"Fenqing là người như thế nào ?", {"entities": [(0, 7, "PER")]}),
            (u"Thường thì Fenqing là người dưới hai mươi tuổi , tuy đôi lúc có những kẻ hơn hai mươi tuổi cũng được coi là Fenqing .", {"entities": [(11, 18, "PER"),(108, 115, "PER")]}),
            (u"Tuy bạn có thể thấy đa số các Fenqing trong số học sinh trung học và sinh viên cao đẳng , nhưng tuổi tác không phải là đặc điểm quan trọng nhất .", {"entities": [(30, 37, "PER")]}),
            (u"Điều thực sự quan trọng là cách họ nhìn nhận về Trung Quốc và thế giới .", {"entities": [(48, 58, "LOC")]}),
            (u"Fenqing không biết những gì ?", {"entities": [(0, 7, "PER")]}),
            (u"Việc mà đa số Fenqing không hiểu biết nhiều thứ là yếu tố để xác định ý kiến và quan điểm của họ về thế giới và Trung Quốc .", {"entities": [(14, 21, "PER"),(112, 122, "LOC")]}),
            (u"Một Fenqing tiêu biểu không biết trả lời những câu hỏi sau :", {"entities": [(4, 11, "PER")]}),
            (u"Fenqing tin rằng ba thứ này về cơ bản là giống nhau .", {"entities": [(0, 7, "PER")]}),
            (u"Lãnh thổ Trung Quốc rộng bao nhiêu và diện tích đất của nó đứng hàng thứ mấy ?", {"entities": [(9, 19, "LOC")]}),
            (u"Fenqing được dạy dỗ rằng Trung Quốc là quốc gia lớn thứ ba trên thế giới , và họ không bao giờ biết rằng nó đã thu hẹp chút ít .", {"entities": [(0, 7, "ORG"),(25, 35, "LOC")]}),
            (u"Fenqing vốn biết rõ hoặc quan tâm mình thực sự là người đóng thuế và có quyền biết tiền thuế của họ được sử dụng như thế nào .", {"entities": [(0, 7, "PER")]}),
            (u"Quan điểm của Fenqing là gì ?", {"entities": [(14, 21, "PER")]}),
            (u"Hoa Kỳ là một khối thống nhất .", {"entities": [(0, 6, "LOC")]}),
            (u"Mỹ xấu , xấu và xấu vì Bush xấu .", {"entities": [(0, 2, "ORG"),(23, 27, "PER")]}),
            (u"Chống Nhật Bản và kêu gọi tẩy chay hàng Nhật Bản trong khi vẫn thích xem phim sex và phim hoạt hình Nhật Bản .", {"entities": [(6, 14, "LOC"),(40, 48, "LOC"),(100, 108, "LOC")]}),
            (u"Thị trường chứng khoán Trung Quốc sa sút là vì âm mưu của đế quốc phương Tây .", {"entities": [(23, 33, "LOC"),(66, 76, "LOC")]}),
            (u"Giá nhà ở Trung quốc tăng vọt là vì các khoản đầu tư ngắn hạn của giới đầu cơ quốc tế .", {"entities": [(10, 20, "LOC")]}),
            (u"Các quốc gia phương Tây do Mỹ cầm đầu đang cố bao vây và kìm hãm Trung Quốc .", {"entities": [(13, 23, "LOC"),(27, 29, "LOC"),(65, 75, "LOC")]}),
            (u"CNN xấu vì CNN nói láo , nhưng CCTV điều chỉnh thông tin để duy trì ổn định xã hội thì không sao .", {"entities": [(0, 3, "ORG"),(11, 14, "ORG"),(31, 35, "ORG")]}),
            (u"Vai trò của Fenqing ở Trung quốc là gì ?", {"entities": [(12, 19, "PER"),(22, 32, "LOC")]}),
            (u"Fenqing thường là tự phát , nhưng dễ thổi bùng cái thói cuồng nhiệt mù quáng của họ - chỉ cần bảo với họ là Trung Quốc đã bị tấn công .", {"entities": [(0, 7, "PER"),(108, 118, "LOC")]}),
            (u"Fenqing không phải là những người yêu nước", {"entities": [(0, 7, "PER")]}),
            (u"Trung Quốc là phần nối dài nhất của một nền văn minh , và trong nhiều thế kỷ , nó đã đứng đầu thế giới do các thành tựu kinh tế và phát minh kỹ thuật của họ .", {"entities": [(0, 10, "LOC")]}),
            (u"Nỗi thống khổ và tủi nhục vô biên trong hơn một thế kỷ đã làm người dân Trung Quốc bị tổn thương sâu sắc .", {"entities": [(72, 82, "LOC")]}),
            (u"Nó đã trở thành giấc mơ của dân tộc Trung Quốc việc đánh đuổi quân xâm lược và thực dân phương tây , và lại vươn lên trên thế giới một cách vinh quang và đường hoàng .", {"entities": [(36, 46, "LOC")]}),
            (u"Rõ ràng đây là cội nguồn của lòng yêu nước và chủ nghĩa dân tộc của Trung Hoa .", {"entities": [(68, 77, "LOC")]}),
            (u"Do hận thù có căn cơ đối với thực dân phương Tây và quân xâm lược trong quá khứ ( nhất là Nhật Bản ) , Fenqing là một nhóm người vờ không thấy những vấn đề trong nước hoặc chỉ cần đổ thừa mọi thứ xấu xa cho bọn đế quốc .", {"entities": [(90, 98, "LOC"),(103, 110, "PER")]}),
            (u"Fenqing không đủ tiêu chuẩn để được gọi là người yêu nước vì lý do đơn giản là họ không biết ba khái niệm chính trị đơn giản mà tôi đã đề cập ở trên .", {"entities": [(0, 7, "PER")]}),
            (u"Ai đã tạo ra Fenqing ?", {"entities": [(13, 20, "PER")]}),
            (u"Khi tôi chiếu một bộ phim về chiến tranh ở Iraq - No End in Sight - cho một nhóm sinh viên cao đẳng , một sinh viên đã đến chỗ tôi và nói :", {"entities": [(43, 47, "LOC")]}),
            (u"Tôi ngạc nhiên khi nghe những điều cô ấy nói , và kể cho cô ấy nghe những chuyện Saddam đã làm đối với người Kurd ở miền bắc Iraq và chuyện ông ta từng được chính phủ Hoa Kỳ hỗ trợ trong cuộc chiến Iran-Iraq .", {"entities": [(81, 87, "PER"),(109, 113, "PER"),(125, 129, "LOC"),(167, 173, "LOC"),(198, 207, "LOC")]}),
            (u"Liệu Fenqing có mãi mãi là Fenqing không ?", {"entities": [(5, 12, "PER"),(27, 34, "PER")]}),
            (u"Lịch sử của hoa Tulip từ Thổ Nhĩ Kỳ đến Hà lan", {"entities": [(25, 35, "LOC"),(40, 46, "LOC")]}),
            (u"Hoa Tulip có nguồn gốc là loài hoa dại mọc ở vùng Trung Á và được người Thổ Nhĩ Kỳ trồng đầu tiên ngay từ năm 1000 sau Công nguyên .", {"entities": [(50, 57, "LOC"),(72, 82, "LOC"),(106, 130, "TIM")]}),
            (u"Hoa được đưa vào Tây Âu và Hà Lan vào thế kỷ 17 bởi Carolus Clusius , một nhà nghiên cứu sinh vật học của Vienna .", {"entities": [(17, 23, "LOC"),(27, 33, "LOC"),(38, 47, "TIM"),(52, 67, "PER"),(106, 112, "LOC")]}),
            (u"Vào năm 1590 ông ấy trở thành giám đốc của Hortus Botanicus ở Leiden , một vườn bách thảo xưa nhất của Châu Âu , được thành lập năm 1587 .", {"entities": [(4, 12, "TIM"),(43, 59, "ORG"),(62, 68, "LOC"),(103, 110, "LOC"),(128, 136, "TIM")]}),
            (u"Ông ấy được trường đại học Leiden thuê về làm nghiên cứu các loài thực vật có dược tính và trong khi làm việc này ông ấy nhận được vài củ từ Thổ Nhĩ Kỳ do bạn ông Ogier Ghiselain de Busbecq , một đại sứ của Constantinople gởi tới .", {"entities": [(12, 33, "ORG"),(141, 151, "LOC"),(163, 189, "PER"),(207, 221, "LOC")]}),
            (u"Ngoài mục đích dùng làm thảo dược như trước kia , vào đầu thế kỷ 17 hoa Tulip được dùng để trang trí khu vườn .", {"entities": [(58, 67, "TIM")]}),
            (u"Chẳng bao lâu nó đã được biết rộng rãi như một sản phẩm thương mại , nhất là ở Hà lan .", {"entities": [(79, 85, "LOC")]}),
            (u"Vài mẫu có thể mua đắt hơn cả một ngôi nhà ở Amsterdam lúc bấy giờ .", {"entities": [(45, 54, "LOC")]}),
            (u"Vào thế kỷ 20 người ta phát hiện ra rằng cánh hoa có diềm xếp nếp và ánh hồng thật ấn tượng mang lại cho hoa vẻ ngoài hấp dẫn , mà thực tế là triệu chứng của chứng bệnh lây lan do vi rút bệnh khảm .", {"entities": [(4, 13, "TIM")]}),
            (u"Phát hiện sơ bộ của điều tra viên : Jackson đã dùng propofol quá liều", {"entities": [(36, 43, "PER")]}),
            (u"( CNN ) - Điều tra viên của Los Angeles đã kết luận sơ bộ rằng ca sĩ Michael Jackson chết do dùng propofol quá liều , một loại thuốc giảm đau mạnh giúp anh ấy có thể ngủ được , theo văn kiện của toà án đã công bố vào ngày thứ Hai .", {"entities": [(2, 5, "ORG"),(28, 39, "LOC"),(69, 84, "PER"),(217, 229, "TIM")]}),
            (u"Lệnh khám xét đã đệ trình tại tòa cho thấy báo cáo xét nghiệm độc tố phát hiện trong cơ thể của Michael Jackson có propofol .", {"entities": [(96, 111, "PER")]}),
            (u"Bác sĩ Lakshmanan Sathyavagiswaran , điều tra viên ở Los Angeles , đã đưa ra kết luận sơ bộ sau khi xem xét kết quả xét nghiệm độc tố trong máu của Jackson , theo lệnh khám xét và bản khai có tuyên thệ chưa được đóng dấu tại Houston , Texas .", {"entities": [(7, 34, "PER"),(53, 64, "LOC"),(148, 155, "PER"),(225, 232, "LOC"),(235, 240, "LOC")]}),
            (u"Bản khai này được dùng để vạch ra nguyên do mà có thể dựa vào đó để đưa ra lệnh khám xét phòng mạch của những bác sĩ được cho là đã chữa trị cho Jackson , đã tiết lộ nhiều thông tin về những loại thuốc đã cho Jackson trong những tuần trước khi anh ấy chết .", {"entities": [(145, 152, "PER"),(209, 216, "PER")]}),
            (u"Associated Press đã viện dẫn một nhân viên công lực , người từng nói rằng Điều tra viên Hạt L.A. đã quy kết cái chết của Michael Jackson là một vụ án mạng .", {"entities": [(0, 16, "ORG"),(88, 96, "LOC"),(121, 136, "PER")]}),
            (u"Người phát ngôn của LAPD cho rằng chuyện này không phải đến từ sở cảnh sát .", {"entities": [(20, 24, "ORG")]}),
            (u"Bản chứng nhận dài 32 trang cho rằng bác sĩ Conrad Murray , bác sĩ riêng của Jackson , đã kể với thám tử rằng ông ấy đã điều trị chứng mất ngủ cho Jackson trong sáu tuần .", {"entities": [(44, 57, "PER"),(77, 84, "PER"),(147, 154, "PER")]}),
            (u"Murray nói mỗi đêm ông ấy cho Jackson dùng 50 mg thuốc propofol , cũng gọi là Diprivan , được pha loãng với Lidocaine gây tê cục bộ bằng cách truyền qua tĩnh mạch .", {"entities": [(0, 6, "PER"),(30, 37, "PER")]}),
            (u"Lo ngại rằng Jackson có thể bị nghiện thuốc , bác sĩ tim mạch ở Houston nói ông ấy cố cai thuốc cho anh ấy bằng cách phối hợp với nhiều loại thuốc từng giúp cho Jackson ngủ được trong hai đêm trước khi anh ấy chết .", {"entities": [(13, 20, "PER"),(64, 71, "LOC"),(161, 168, "PER")]}),
            (u"Theo tài liệu có được , Murray nói rằng vào ngày 22 tháng sáu ông ấy cho Jackson dùng một hỗn hợp thuốc tương tự như hỗn hợp mà ông ấy cho anh ấy dùng trong ngày anh ấy chết , ngày 25 tháng sáu - đó chính là propofol , Ativan và Versed , tức là những loại thuốc từng giúp ngôi sao ngủ thiếp đi .", {"entities": [(24, 30, "PER"),(44, 61, "TIM"),(73, 80, "PER"),(176, 193, "TIM")]}),
            (u"Vào ngày 23 tháng sáu ông ấy chỉ đưa cho Jackson thuốc Ativan và Versed , giúp anh ấy ngủ được .", {"entities": [(4, 21, "TIM"),(41, 48, "PER")]}),
            (u"Nhưng vào ngày 25 tháng sáu , những loại thuốc khác không hiệu quả , theo như Murray thuật lại cho các thám tử trong một bản tường trình chi tiết về thời giờ do thám tử Orlando Martinez thuộc sở cảnh sát Los Angeles .", {"entities": [(10, 27, "TIM"),(78, 84, "PER"),(169, 185, "PER"),(192, 215, "ORG")]}),
            (u"Vào khoảng 1:30 sáng , Murray tiêm cho Jackson 10 mg Valium .", {"entities": [(11, 20, "TIM"),(23, 29, "PER"),(39, 46, "PER")]}),
            (u"Vào khoảng 2 sáng , ông ấy tiêm Jackson 2 mg thuốc ngủ Ativan .", {"entities": [(11, 17, "TIM"),(32, 39, "PER")]}),
            (u"Vào khoảng 3 sáng , Murray tiêm tiếp 2 mg thuốc giảm đau Versed .", {"entities": [(11, 17, "TIM"),(20, 26, "PER")]}),
            (u"Vào khoảng 5 sáng , ông ấy tiêm thêm 2 mg Ativan nữa .", {"entities": [(11, 17, "TIM")]}),
            (u"Vào khoảng 7:30 sáng , Murray tiêm cho Jackson thêm 2 mg Versed trong khi vẫn đang theo dõi anh ấy với thiết bị đo độ bão hoà ô-xi trong máu .", {"entities": [(11, 20, "TIM"),(23, 29, "PER"),(39, 46, "PER")]}),
            (u"Cuối cùng thì Jackson cũng ngủ được và Murray cho rằng ông ấy vẫn đang tiếp tục theo dõi anh ấy .", {"entities": [(14, 21, "PER"),(39, 45, "PER")]}),
            (u"Sau khoảng 10 phút , Murray nói ông rời khỏi Jackson để đi vệ sinh .", {"entities": [(21, 27, "PER"),(45, 52, "PER")]}),
            (u"Murray nói rằng ông ta ra khỏi phòng trong khoảng tối đa là hai phút .", {"entities": [(0, 6, "PER")]}),
            (u"Khi trở lại , Murray nhận thấy Jackson đã ngưng thở .", {"entities": [(14, 20, "PER"),(31, 38, "PER")]}),
            (u"Theo Murray , những nỗ lực hô hấp nhân tạo đều vô ích .", {"entities": [(5, 11, "PER")]}),
            (u"Chẳng bao lâu sau khi Murray nói ông ấy phát hiện Jackson không còn thở nữa , Murray nói chuyện trên điện thoại với ba người khác nhau bắt đầu từ lúc 11:18 sáng và kết thúc vào lúc 12:05 trưa , theo văn kiện toà án có trích dẫn ghi chép từ số điện thoại của bác sĩ .", {"entities": [(22, 28, "PER"),(50, 57, "PER"),(78, 84, "PER"),(150, 160, "TIM"),(181, 191, "TIM")]}),
            (u"Chernoff phủ nhận trình tự ghi trong bản khai .", {"entities": [(0, 8, "PER")]}),
            (u"Vô lý nhất là trình tự thời gian do cơ quan công quyền ghi nhận không được thu thập qua cuộc chất vấn bác sĩ Murray , như đã được nhắc tới trong bản khai .", {"entities": [(109, 115, "PER")]}),
            (u"Bác sĩ Murray chưa bao giờ kể cho các điều tra viên là ông ấy phát hiện Michael Jackson ngừng thở vào lúc 11:00 sáng .", {"entities": [(7, 13, "PER"),(72, 87, "PER"),(106, 116, "TIM")]}),
            (u"Ông ấy cũng không bao giờ nói rằng ông ấy đợi trong 10 phút trước khi rời khỏi để gọi vài cuộc điện thoại .", {"entities": [(52, 54, "TIM")]}),
            (u"Thực ra , bác sĩ Murray không bao giờ nói rằng ông ấy đã rời khỏi phòng của Michael Jackson để gọi bất kỳ cuộc điện thoại nào cả .", {"entities": [(17, 23, "PER"),(76, 91, "PER")]}),
            (u"Văn kiện còn liệt kê thêm năm vị bác sĩ và một y sĩ được cho là đã điều trị cho Jackson .", {"entities": [(80, 87, "PER")]}),
            (u"Jackson cũng kể với Murray về hai bác sĩ ở Đức không rõ danh tính mà đã từng cho anh ấy dùng propofol .", {"entities": [(0, 7, "PER"),(20, 26, "PER"),(43, 46, "LOC")]}),
            (u"Văn kiện cho biết cảnh sát đã tìm thấy tám chai thuốc propofol trong nhà của Jackson .", {"entities": [(77, 84, "PER")]}),
            (u"Lục soát túi đồ nghề của bác sĩ Murray mà ông ta đã bỏ ở nhà vào ngày Jackson chết thì thấy có rất nhiều chai lọ thuốc Lidocaine và vài chai lọ thuốc propofol , Ativan , Versed và Anexate .", {"entities": [(32, 38, "PER"),(70, 77, "PER")]}),
            (u"Luật sư của Metzger nói với CNN hồi tháng trước rằng Metzger - người từng điều trị cho Jackson vào năm 2003 - đã không cho Jackson dùng propofol theo như anh ta yêu cầu vào tháng 4 .", {"entities": [(12, 19, "PER"),(28, 31, "ORG"),(53, 60, "PER"),(87, 94, "PER"),(99, 107, "TIM"),(123, 130, "PER"),(173, 180, "TIM")]}),
            (u"Klein - bác sĩ chuyên khoa da liễu cũng là một người bạn lâu năm của Jackson - đã nhấn mạnh rằng ông ta chưa bao giờ cho Jackson dùng loại thuốc nguy hiểm nào cả .", {"entities": [(0, 5, "PER"),(69, 76, "PER"),(121, 128, "PER")]}),
            (u"Jackson đến khám tại phòng mạch của bác sĩ Klein ở Beverly Hills , California , chỉ vài ngày trước khi anh ấy qua đời vào ngày 25 tháng 6 .", {"entities": [(0, 7, "PER"),(43, 48, "PER"),(51, 64, "LOC"),(67, 77, "LOC"),(122, 137, "TIM")]}),
            (u"Murray trở thành bác sĩ riêng cho Jackson vào tháng 5 , khi ngôi sao nhạc Pop này đang chuẩn bị cho một loạt chương trình biểu diễn trở lại sẽ bắt đầu vào tháng 7 tại sân vận động O2 ở Luân Đôn .", {"entities": [(0, 6, "PER"),(34, 41, "PER"),(46, 53, "TIM"),(155, 162, "TIM"),(180, 182, "LOC"),(185, 193, "LOC")]}),
            (u"Murray nói với các điều tra viên là Jackson không hề kể cho ông ấy nghe các bác sĩ khác đã cho anh ấy uống thuốc gì , nhưng anh ấy có nói với Murray thuốc do bác sĩ Klein và Metzger thì không công hiệu .", {"entities": [(0, 6, "PER"),(36, 43, "PER"),(142, 148, "PER"),(165, 170, "PER"),(174, 181, "PER")]}),
            (u"Văn kiện cũng cho hay DEA vẫn chưa tìm được ghi chép nào của bác sĩ Murray về việc mua , đặt hàng hoặc có được bất kỳ thuốc propofol nào do giấy phép hành nghề của ông ấy hoặc số DEA .", {"entities": [(22, 25, "ORG"),(61, 74, "PER"),(179, 182, "ORG")]}),
            (u"Tuần này chúng tôi kết thúc câu chuyện về nhà văn kiêm nhà giáo dục , Helen Keller .", {"entities": [(70, 82, "PER")]}),
            (u"Chúng tôi đã bàn hồi tuần trước , Helen Keller mắc một căn bệnh lạ khi cô ấy mới 19 tháng tuổi .", {"entities": [(34, 46, "PER")]}),
            (u"Sau đó , một giáo viên - Anne Sullivan - đến từ Boston đã giúp cô ấy .", {"entities": [(25, 38, "PER"),(48, 54, "LOC")]}),
            (u"Cô Sullivan cũng từng bị mù .", {"entities": [(3, 11, "PER")]}),
            (u"Cô ấy cố dạy Helen cách sống như những người khác .", {"entities": [(13, 18, "PER")]}),
            (u"Cô Sullivan dẫn Helen vào rừng để tìm hiểu thiên nhiên .", {"entities": [(3, 11, "PER"),(16, 21, "PER")]}),
            (u"Cô Sullivan giải thích tất cả ngôn ngữ cô ấy và Helen sử dụng - ngôn ngữ của xúc giác - của ngón tay và bàn tay .", {"entities": [(3, 11, "PER"),(48, 53, "PER")]}),
            (u"Helen cũng học cách cưỡi ngựa , bơi , chèo thuyền và thậm chí còn trèo cây .", {"entities": [(0, 5, "PER")]}),
            (u"Helen Keller từng viết về những ngày thơ ấu này .", {"entities": [(0, 12, "PER")]}),
            (u"Một buổi sáng mùa xuân tươi đẹp , tôi ở một mình trong phòng đọc sách .", {"entities": [(14, 22, "TIM")]}),
            (u"Nàng xuân dường như đang ghé ngang qua phòng tôi .", {"entities": [(0, 9, "TIM")]}),
            (u"Sau đó , Helen biết rằng thiên nhiên có thể vừa khắc nghiệt nhưng lại vừa xinh đẹp .", {"entities": [(9, 14, "PER")]}),
            (u"Cô Sullivan leo với tôi .", {"entities": [(3, 11, "PER")]}),
            (u"Cô Sullivan tiếp tục sống cùng Helen trong nhiều năm .", {"entities": [(3, 11, "PER"),(31, 36, "PER")]}),
            (u"Cô ấy dạy Helen cách đọc , viết và nói .", {"entities": [(10, 15, "PER")]}),
            (u"Cô giúp Helen chuẩn bị vào học ở trường và cao đẳng .", {"entities": [(8, 13, "PER")]}),
            (u"Hơn bất cứ thứ gì , Helen muốn làm những gì người khác làm , và làm thật tốt .", {"entities": [(20, 25, "PER")]}),
            (u"Đến lúc này , Helen đã đi học cao đẳng và tốt nghiệp loại ưu .", {"entities": [(14, 19, "PER")]}),
            (u"Cô Sullivan và những người khác phải dạy cô những điều trong sách bằng cách viết chữ vào tay .", {"entities": [(3, 11, "PER")]}),
            (u"Trong năm thứ nhì của cô ấy ở trường cao đẳng , Cô Keller đã viết câu chuyện về đời mình và ngôi trường này có ý nghĩa như thế nào đối với cô .", {"entities": [(51, 57, "PER")]}),
            (u"Ngày đầu tiên của tôi ở Trường cao đẳng Radcliffe thật thú vị .", {"entities": [(24, 49, "ORG")]}),
            (u"Tất cả những kiến thức Helen Keller có được trong đầu mình là nhờ các giác quan của xúc giác và vị khứu giác , và dĩ nhiên là cảm giác của cô ấy nữa .", {"entities": [(23, 35, "PER")]}),
            (u"Thoát khỏi thế giới của bóng tối và tĩnh lặng , Helen Keller đã mang hi vọng đến hàng triệu con người", {"entities": [(48, 60, "PER")]}),
            (u"Cái tên Helen Keller có một ý nghĩa đặc biệt đối với hàng triệu người khắp nơi trên thế giới .", {"entities": [(8, 20, "PER")]}),
            (u"Tuy nhiên Helen Keller đã có thể làm được rất nhiều việc ngày này qua năm nọ của mình .", {"entities": [(10, 22, "PER")]}),
            (u"Helen Keller sinh ra ngày 22 tháng 6 , năm 1880 tại một thành phố nhỏ miền bắc Alabama .", {"entities": [(0, 12, "PER"),(21, 36, "TIM"),(39, 47, "TIM"),(79, 86, "LOC")]}),
            (u"Cha cô ấy , Arthur Keller , là đại uý quân đội miền Nam trong cuộc nội chiến Mỹ .", {"entities": [(12, 25, "PER"),(77, 79, "LOC")]}),
            (u"Helen là con đầu lòng của họ .", {"entities": [(0, 5, "PER")]}),
            (u"Cho đến năm cô ấy được một tuổi rưỡi , Helen Keller giống như mọi đứa trẻ khác .", {"entities": [(39, 51, "PER")]}),
            (u"Sau đó , khi được 19 tháng tuổi , Helen lâm bệnh nặng .", {"entities": [(34, 39, "PER")]}),
            (u"Từ lúc đó cho đến khi gần bảy tuổi , Helen chỉ có thể giao tiếp bằng cách ra dấu hiệu bằng tay .", {"entities": [(37, 42, "PER")]}),
            (u"Khi Helen lên sáu , cha cô nghe nói có một ông bác sĩ ở Baltimore , Maryland .", {"entities": [(4, 9, "PER"),(56, 65, "LOC"),(68, 76, "LOC")]}),
            (u"Cha mẹ của Helen đưa cô ấy đi bằng xe lửa đến Baltimore .", {"entities": [(11, 16, "PER"),(46, 55, "LOC")]}),
            (u"Nhưng ông bác sĩ nói ông ấy không thể giúp gì cho Helen .", {"entities": [(50, 55, "PER")]}),
            (u"Ông ta đề nghị gia đình Kellers kiếm một giáo viên chuyên dạy cho người mù để dạy Helen cách giao tiếp .", {"entities": [(24, 31, "PER"),(82, 87, "PER")]}),
            (u"Có một giáo viên đến từ Trường Perkins dành cho người khiếm thị ở Boston .", {"entities": [(24, 38, "ORG"),(66, 72, "LOC")]}),
            (u"Tên của cô ta là Anne Sullivan .", {"entities": [(17, 30, "PER")]}),
            (u"Ở Perkins , cô đã học được các phương pháp mới nhất để dạy cho người mù .", {"entities": [(2, 9, "ORG")]}),
            (u"Anne Sullivan bắt đầu bằng cách dạy cho Helen biết rằng mọi thứ đều có một cái tên .", {"entities": [(0, 13, "PER"),(40, 45, "PER")]}),
            (u"Helen phải học cách sử dụng bàn tay và các ngón tay để nói thay cho mình .", {"entities": [(0, 5, "PER")]}),
            (u"Cô Sullivan nhanh chóng hiểu được điều này .", {"entities": [(3, 11, "PER")]}),
            (u"Cô ấy viết thư cho bạn bè ở Boston về những kinh nghiệm cô đã dạy cho Helen .", {"entities": [(28, 34, "LOC"),(70, 75, "PER")]}),
            (u"Đêm đầu tiên tôi đến tôi đã cho Helen một con búp bê .", {"entities": [(32, 37, "PER")]}),
            (u"Helen ngồi dưới sàn nhà , đá lung tung , la hét và cố lôi kéo chiếc ghế tôi đang ngồi .", {"entities": [(0, 5, "PER")]}),
            (u"Vì thế tôi yêu cầu họ để tôi cùng Helen dời đến một căn nhà nhỏ có một phòng gần đó .", {"entities": [(34, 39, "PER")]}),
            (u"Ngày đầu tiên xa gia đình Helen đá lung tung và la hét suốt .", {"entities": [(26, 31, "PER")]}),
            (u"Helen học nhanh .", {"entities": [(0, 5, "PER")]}),
            (u"Tôi đặt tay Helen dưới dòng nước lạnh và viết các chữ cái w-a-t-e-r trong tay kia của cô bé .", {"entities": [(12, 17, "PER")]}),
            (u"Helen nhìn lên bầu trời như thể ký ức đã bị đánh mất hay một ý nghĩ gì đó đang tràn về trong cô bé .", {"entities": [(0, 5, "PER")]}),
            (u"Từ lúc đó mỗi ngày Helen rời khỏi nhà , tìm kiếm mọi thứ để học .", {"entities": [(19, 24, "PER")]}),
            (u"Một hôm nọ , Helen nhớ lại con búp bê cô bé đã làm vỡ .", {"entities": [(13, 18, "PER")]}),
            (u"Cô Sullivan dạy cho Helen nhiều thứ - đọc và viết , và thậm chí sử dụng máy đánh chữ .", {"entities": [(3, 11, "PER"),(20, 25, "PER")]}),
            (u"Nhưng quan trọng nhất , cô ấy dạy Helen cách suy nghĩ .", {"entities": [(34, 39, "PER")]}),
            (u"Trong ba năm sau đó , Helen học ngày càng nhiều từ mới .", {"entities": [(22, 27, "PER")]}),
            (u"Suốt ngày cô Sullivan chạm vào tay của Helen , đánh vần và nói cho Helen một ngôn ngữ .", {"entities": [(13, 21, "PER"),(39, 44, "PER"),(67, 72, "PER")]}),
            (u"Đồng thời , Helen tỏ ra mình có thể học được những ngoại ngữ khác .", {"entities": [(12, 17, "PER")]}),
            (u"Cô ấy học tiếng La-tinh , Hy Lạp , Pháp và Đức .", {"entities": [(16, 23, "LOC"),(26, 32, "LOC"),(35, 39, "LOC"),(43, 46, "LOC")]}),
            (u"Helen còn có thể học nhiều thứ , không riêng gì ngôn ngữ .", {"entities": [(0, 5, "PER")]}),
            (u"Một lần , cô Sullivan đề nghị để một bài toán sang ngày hôm sau giải tiếp .", {"entities": [(13, 21, "PER")]}),
            (u"Nhưng Helen vẫn muốn tiếp tục làm .", {"entities": [(6, 11, "PER")]}),
            (u"Helen đi du lịch nhiều với gia đình hoặc đi riêng với cô Sullivan .", {"entities": [(0, 5, "PER"),(57, 65, "PER")]}),
            (u"Vào năm 1888 , Helen , mẹ cô và cô Sullivan đi Boston , Massachusetts .", {"entities": [(4, 12, "TIM"),(15, 20, "PER"),(35, 43, "PER"),(47, 53, "LOC"),(56, 69, "LOC")]}),
            (u"Họ đi thăm trường Perkins nơi cô Sullivan đã học nghề sư phạm .", {"entities": [(11, 25, "ORG"),(33, 41, "PER")]}),
            (u"Họ ở lại đó gần hết mùa hè tại nhà của bạn bè của gia đình gần biển Đại Tây Dương .", {"entities": [(20, 26, "TIM"),(68, 81, "LOC")]}),
            (u"Trong lần trải nghiệm về biển đầu tiên của Helen , cô bị sóng cuốn và chìm xuống nước .", {"entities": [(43, 48, "PER")]}),
            (u"Cô Sullivan đã cứu cô .", {"entities": [(3, 11, "PER")]}),
            (u"Ba năm sau Helen bắt đầu giao tiếp bằng tay , cô ấy bắt đầu học nói như những người khác .", {"entities": [(11, 16, "PER")]}),
            (u"Những ngày đầu tiên Helen Keller phát triển khả năng nói thật kỳ diệu .", {"entities": [(20, 32, "PER")]}),
            (u"Cách đây mười hai năm , đạo diễn kiêm kịch bản phim James Cameron đã làm nên Titanic , một thiên tình sử lãng mạn đã trở thành bộ phim có doanh thu cao nhất trong lịch sử Hollywood .", {"entities": [(52, 65, "PER"),(171, 180, "ORG")]}),
            (u"Jake Sully là chiến binh bị thương : một người lính thuỷ quân lục chiến Mỹ bị liệt chân từ một chấn thương trên chiến trường .", {"entities": [(0, 10, "PER"),(72, 74, "LOC")]}),
            (u"Anh không còn ở Kansas nữa .", {"entities": [(16, 22, "LOC")]}),
            (u"Anh đang ở trên Pandora .", {"entities": [(16, 23, "LOC")]}),
            (u"Dường như Pandora là nơi duy nhất trong thiên hà chứa đựng nhiều trầm tích của một nguồn năng lượng mới quý giá mà khi mang về đất thì không ai biết được chúng có giá trị bao nhiêu triệu đô la .", {"entities": [(10, 17, "LOC")]}),
            (u"Tuy nhiên , để lấy được nó , họ phải xâm nhập … hoặc tống khứ … bộ tộc Pandora : một bộ tộc cao lớn , da màu xanh dương gọi là người Navi .", {"entities": [(71, 78, "LOC")]}),
            (u"Đó là nơi mà Jake và những đồng nghiệp của anh ấy thâm nhập vào :", {"entities": [(13, 17, "PER")]}),
            (u"Với trí óc được liên kết bằng điện tử vào cơ thể Hiện thân , Jake không những có thể đi đứng trở lại và tồn tại trong bầu khí quyển độc hại của Pandora , anh ấy còn có thể tiếp xúc trực tiếp với người Navi .", {"entities": [(61, 65, "PER"),(144, 151, "LOC")]}),
            (u"Nhưng khi cô gái xinh đẹp Neytiri kể cho Jake về người Navi và sự kết nối của họ với thế giới , anh ấy trở nên tin tưởng rằng cuộc khai thác của những người cộng sự của anh phải được ngăn chặn lại .", {"entities": [(26, 33, "PER"),(41, 45, "PER")]}),
            (u"Sam Worthington , người gốc New Zealand , thủ vai Jake và Zoe Saldana người New Jersey đóng vai Neytiri .", {"entities": [(0, 15, "PER"),(28, 39, "LOC"),(50, 54, "PER"),(58, 69, "PER"),(76, 86, "LOC"),(96, 103, "PER")]}),
            (u"Cameron , người sinh ra ở Canada , đã mất nhiều năm phát triển công nghệ chụp kỹ thuật số các cử động diễn xuất cho các nhân vật trong Avatar .", {"entities": [(0, 7, "PER"),(26, 32, "LOC")]}),
            (u"Tôi làm việc với các diễn viên , Cameron chú thích .", {"entities": [(33, 40, "PER")]}),
            (u"Cameron cũng khai phá công nghệ 3D thực đòi hỏi khán giả phải đeo loại mắt kính đặc biệt ; nhưng Sam Worthington nói nó sẽ đưa họ theo cùng anh ấy trong các pha hành động .", {"entities": [(0, 7, "ORG"),(97, 112, "PER")]}),
            (u"Chúng tôi đã không hề bị mất việc vì những nhân vật CG chỉ có thể làm việc khi chúng tôi hiện thân vào nó và tôi có thể cam đoan rằng 100% rằng đó là diễn xuất của chính Zoe và tôi .", {"entities": [(134, 138, "PCT"),(170, 173, "PER")]}),
            (u"Đó là một thủ thuật và ma thuật của bộ phim này mà Jim và WETA Digital đã phải tự thôi thúc mình đi thẳng vào mục tiêu nơi mà chúng tôi quên đi rằng chúng tôi đang nhìn những giống người cao to da xanh và chúng tôi chỉ bắt đầu cắm rễ vào con người bên trong lòng họ .", {"entities": [(51, 54, "PER"),(58, 70, "ORG")]}),
            (u"Đạo diễn kiêm kịch bản Cameron cũng thừa nhận là những gì con người cố làm trên hành tinh hư cấu Pandora chỉ là một ẩn dụ rõ ràng cho những gì ông ấy tin là những mối đe doạ của việc khai thác trên hành tinh của chúng ta .", {"entities": [(23, 30, "PER"),(97, 104, "LOC")]}),
            (u"Avatar cũng có sự tham gia của diễn viên từng tham gia phim khoa học giả tưởng Sigourney Weaver vào vai một nhà khoa học tạo ra chương trình để học và tìm hiểu người Navi .", {"entities": [(79, 95, "PER")]}),
            (u"Giovanni Ribisi đóng vai người quản lý dự án khai thác Pandora với Stephen Lang vào vai sĩ quan bán quân sự chỉ huy quân đội và diễn viên người thổ dân châu Mỹ Studi Wes đóng vai tộc trưởng Navi .", {"entities": [(0, 15, "PER"),(55, 62, "LOC"),(67, 79, "PER"),(152, 159, "LOC"),(160, 169, "PER")]}),
            (u"Nhạc nền được soạn bởi nhạc sĩ James Horner , người từng cộng tác với James Cameron trong bộ phim đoạt nhiều giải Oscar Titanic .", {"entities": [(31, 43, "PER"),(70, 83, "PER")]}),
            (u"Bánh Chưng Bánh Dày – truyện kể ngày Tết của Việt Nam", {"entities": [(45, 53, "LOC")]}),
            (u"Ngày xưa , ở Việt Nam có một vị vua già tên là Hùng Vương .", {"entities": [(13, 21, "LOC"),(47, 57, "PER")]}),
            (u"Vua Hùng ngày một già và đã đến lúc trao ngôi báu lại cho người nối ngôi , vua chỉ băn khoăn một điều là Vua Hùng có ba hoàng tử khỏe mạnh và không biết phải chọn ai trong số họ .", {"entities": [(0, 8, "PER"),(105, 113, "PER")]}),
            (u"Vua Hùng rất khôn ngoan và suy nghĩ cặn kẽ về việc này và Ngài đã nảy ra một cách giải quyết rất đúng lúc .", {"entities": [(0, 8, "PER")]}),
            (u"Hỡi các con , các con đều thông minh và khỏe mạnh nhưng chỉ một trong các con có thể trị vì nước Việt Nam yêu dấu của chúng ta .", {"entities": [(97, 105, "LOC")]}),
            (u"Hết thảy quần thần trong triều và ba hoàng tử đều lắng nghe hết sức chăm chú vì vua Hùng được biết là vị vua trị vì thông minh nhất Châu Á .", {"entities": [(84, 88, "PER"),(132, 138, "LOC")]})]
